# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hashtag', models.CharField(blank=True, max_length=255)),
                ('thumbnail_large', models.URLField(default=None, null=True)),
                ('thumbnail_small', models.URLField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('parent_category', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorization.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
