# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0004_auto_20170629_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
