/**
 * Ranked API
 * API for mobile and/or Web Clients
 *
 * OpenAPI spec version: 0.0.8
 * Contact: me@josh.land
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface VideoUploadDetails {
    preSignedUploadUrl?: string;

    /**
     * Generated Video ID that can be used to check status and update any values on /videos
     */
    videoId?: number;

}
