/**
 * Ranked API
 * API for mobile and/or Web Clients
 *
 * OpenAPI spec version: 0.0.8
 * Contact: me@josh.land
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Video {
    id?: number;

    title?: string;

    rank?: number;

    isFeatured?: boolean;

    category?: string;

    subCategory?: string;

    likes?: number;

    uploadedBy?: models.User;

}
