# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20170623_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='video.Video'),
        ),
    ]
