# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentstate',
            name='is_updating_favorite_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmentstate',
            name='last_updated_favorite_categories',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
