# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20170701_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranked_ten_count',
            field=models.IntegerField(default=0),
        ),
    ]
