# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0005_auto_20170701_0200'),
        ('profile', '0005_profile_ranked_ten_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_category', to='categorization.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_fav_category', to='categorization.Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followed_profiles',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
