# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20170704_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=256, unique=True),
        ),
    ]
