/**
 * Ranked API
 * API for mobile and/or Web Clients
 *
 * OpenAPI spec version: 0.0.8
 * Contact: me@josh.land
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class SearchApi {
    protected basePath = 'http://dev.goranked.com/api/v1';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * Search for Content
     * 
     * @param category Search by specific category. ex: \&quot;Food\&quot;
     * @param subCategory Search by specific sub-category. ex: Latin
     * @param types Comma delimited list of search result types (see models re: Search Types). ex: Video,Users
     * @param sort NOTE: Ignored for Alpha - always top - sort order (see models re: Sort Criteria)
     */
    public getSearchResults(category?: string, subCategory?: string, types?: string, sort?: string, extraHttpRequestParams?: any): Observable<models.SearchResult> {
        return this.getSearchResultsWithHttpInfo(category, subCategory, types, sort, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * Search for Content
     * 
     * @param category Search by specific category. ex: \&quot;Food\&quot;
     * @param subCategory Search by specific sub-category. ex: Latin
     * @param types Comma delimited list of search result types (see models re: Search Types). ex: Video,Users
     * @param sort NOTE: Ignored for Alpha - always top - sort order (see models re: Sort Criteria)
     */
    public getSearchResultsWithHttpInfo(category?: string, subCategory?: string, types?: string, sort?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/search`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (category !== undefined) {
            if(category instanceof Date) {
                queryParameters.set('category', <any>category.d.toISOString());
            } else {
                queryParameters.set('category', <any>category);
            }
        }

        if (subCategory !== undefined) {
            if(subCategory instanceof Date) {
                queryParameters.set('sub_category', <any>subCategory.d.toISOString());
            } else {
                queryParameters.set('sub_category', <any>subCategory);
            }
        }

        if (types !== undefined) {
            if(types instanceof Date) {
                queryParameters.set('types', <any>types.d.toISOString());
            } else {
                queryParameters.set('types', <any>types);
            }
        }

        if (sort !== undefined) {
            if(sort instanceof Date) {
                queryParameters.set('sort', <any>sort.d.toISOString());
            } else {
                queryParameters.set('sort', <any>sort);
            }
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        // authentication (ranked_auth) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
