# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hashtag', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=256)),
                ('parent_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='video.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hashtag', models.CharField(blank=True, max_length=255)),
                ('thumbnail_large', models.URLField(default=None)),
                ('thumbnail_small', models.URLField(default=None)),
                ('mobile', models.URLField(default=None)),
                ('low', models.URLField(default=None)),
                ('high', models.URLField(default=None)),
                ('hd', models.URLField(default=None)),
                ('pre_signed_upload_url', models.URLField(default=None, null=True)),
                ('title', models.CharField(max_length=256)),
                ('ranking', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Category')),
                ('related_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='video.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
