# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='s3_filename',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
