# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170616_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='s3_filename',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
