# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20170620_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='ranking',
            new_name='rank_total',
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
