# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20170625_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hd',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='high',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='low',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='mobile',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
