# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20170704_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='top_10_ranking',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
