# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20170706_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
