# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_auto_20170722_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
