names_to_purge = """
Demo_SebastianGard_BestCollegeDunk2013-2014OklahomaSt2
Demo_SebastianGard_RachelCollier_OriginalSongs&BeatMakers3
Demo_SebastianGard_RachelCollier_OriginalSongs&BeatMakers2
Demo_SebastianGard_RachelCollier_OriginalSongs&BeatMakers1
Demo_SebastianGard_BestCollegeDunk2013-2014OklahomaSt2
Demo_MelissaShirle_ChlorineandBrakeFluid-science
Demo_MelissaShirle_BalancingCandle-Science
Demo_TimJarrett_BestCosplay2
Demo_JamieSchumacher_OldSchoolFashion1
Demo_FullenWilder_RachelCollier_OriginalSongsBeatMakers4
"""

