# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
